name: AWS-Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
env:
  REGISTRY: '368076259134.dkr.ecr.us-east-1.amazonaws.com'
  REPOSITORY: 'sdk-example'
  IMAGE_TAG: ${{ github.event.repository.name }}
  GCP_PROJECT_ID: "topia-gcp" #${{ secrets.GCP_PROJECT_ID }}
  #GCP_ARTIFACTORY: 'us-west1-docker.pkg.dev'
  GCP_REPOSITORY: 'sdk-apps'
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.16
      #     cache: 'npm'
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::368076259134:role/github-actions-role
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and  tag
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG  .
          
      - name: push docker image to Amazon ECR
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  
      - name: Publish
        run: |
          aws ecs update-service --service sdk-wiggle-dev-topia-svc --force-new-deployment --cluster SDK-Example-CLS
